# Generated by Django 4.2.3 on 2023-07-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizattempt_remove_useranswer_taker_useranswer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='answer',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
