# Generated by Django 4.2.3 on 2023-07-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizattempt_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='answer',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
