# Generated by Django 4.2.3 on 2023-07-19 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_quizattempt_answer_useranswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='answers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.useranswer'),
            preserve_default=False,
        ),
    ]
