# Generated by Django 4.2.3 on 2023-07-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quizattempt_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='answers',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='quiz_attempts', to='quiz.useranswer'),
        ),
    ]
