# Generated by Django 4.2.3 on 2023-07-19 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_useranswer_is_correct_alter_useranswer_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='answers',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='quiz_attempt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.quizattempt'),
            preserve_default=False,
        ),
    ]
